# Generated by Django 3.2.3 on 2021-05-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Published',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('JOUR', 'Journal'), ('CONF', 'Conference'), ('OTHR', 'Others')], default='JOUR', max_length=5)),
                ('year', models.CharField(max_length=4)),
                ('publisher', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('brief', models.TextField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
